/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export interface Note {
  'id' : string,
  'metadata' : NoteMetadata,
  'blob' : ExternalBlob,
}
export interface NoteMetadata {
  'topic' : string,
  'semester' : string,
  'subject' : string,
  'uploader' : Principal,
  'uploadTime' : Time,
  'college' : string,
}
export interface Quiz {
  'id' : string,
  'creator' : Principal,
  'createdAt' : Time,
  'questions' : Array<QuizQuestion>,
}
export interface QuizQuestion {
  'question' : string,
  'answer' : string,
  'options' : Array<string>,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface StudyGroup {
  'id' : string,
  'creator' : Principal,
  'members' : Array<Principal>,
  'name' : string,
  'createdAt' : Time,
  'description' : string,
}
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'isPremium' : boolean,
  'name' : string,
  'email' : string,
  'college' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VivaQuestion {
  'creator' : Principal,
  'question' : string,
  'createdAt' : Time,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createStudyGroup' : ActorMethod<[string, string, string], StudyGroup>,
  'generateQuizFromAI' : ActorMethod<[string], string>,
  'generateSummaryFromAI' : ActorMethod<[string], string>,
  'generateVivaFromAI' : ActorMethod<[string], string>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getNote' : ActorMethod<[string], [] | [Note]>,
  'getNotesBySubject' : ActorMethod<[string], Array<Note>>,
  'getQuiz' : ActorMethod<[string], [] | [Quiz]>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getStudyGroup' : ActorMethod<[string], [] | [StudyGroup]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVivaQuestions' : ActorMethod<[string], Array<VivaQuestion>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'joinStudyGroup' : ActorMethod<[string], StudyGroup>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveQuiz' : ActorMethod<[string, Array<QuizQuestion>], undefined>,
  'saveVivaQuestions' : ActorMethod<[string, Array<string>], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'uploadNote' : ActorMethod<[string, NoteMetadata, ExternalBlob], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];